const placeSynonyms = {
  Party: ["party"],
  Restaurant: ["restaurant", "cafeteria", "cafe", "coffee shop"],
  Home: [
    "home",
    "house",
    "family",
    "mother",
    "father",
    "child",
    "son",
    "daughter",
    "apartment",
  ],
  "Drive-by": ["drive-by", "drive by"],
  Club: ["club", "bar", "pub"],
  School: ["school", "teacher", "student", "university", "college"],
  Street: ["street", "sidewalk", "roadside"],
  "Gas station": ["gas station"],
  "Post office": ["post office"],
  Church: ["church", "temple", "mosque"],
  Mall: ["mall", "shopping", "macy's", "plaza"],
  "Public facilities": [
    "public facilities",
    "city hall",
    "army",
    "government",
    "township",
    "navy",
    "train",
    "airport",
  ],
};

export default placeSynonyms;
